apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saber.databus.fullname" . }}
  labels:
    {{- include "saber.labels" . | nindent 4 }}
    app.kubernetes.io/component: databus
spec:
  replicas: {{ .Values.databus.replicaCount }}
  selector:
    matchLabels:
      {{- include "saber.databus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "saber.databus.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: databus
          image: {{ include "saber.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /app/databus
          args:
            - -c
            - /config/databus.yaml
          ports:
            - name: grpc
              containerPort: 26689
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
          {{- with .Values.databus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "saber.databus.fullname" . }}
      {{- with .Values.databus.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.databus.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
