apiVersion: v1
kind: Service
metadata:
  name: {{ include "saber.databus.fullname" . }}
  labels:
    {{- include "saber.labels" . | nindent 4 }}
    app.kubernetes.io/component: databus
spec:
  type: ClusterIP
  ports:
    - port: 26689
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "saber.databus.selectorLabels" . | nindent 4 }}
